name: AWS Connection & Secret Test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: AWS 인증
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3 버킷 목록 출력
        run: aws s3 ls

      - name: DB_PASSWORD 시크릿 확인
        run: |
          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
            echo "시크릿 값이 없습니다."
            exit 1
          else
            echo "DB_PASSWORD 시크릿이 정상적으로 설정되었습니다."
          fi